/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface ILogin {
  password: string;
  phone: string;
}

export interface ISignup {
  email: string;
  firstName: string;
  lastName: string;
  password: string;
  phone: string;
}
