/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface IExpense {
  data: Date;
  expense: number;
  state: string;
  title: string;
}
